name: Continuous Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install  # Ou "yarn install" si vous utilisez Yarn

      - name: Build application
        run: npm run build  # Ou "yarn build" si vous utilisez Yarn

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.1
        with:
          ssh-private-key: ${{ secrets.DEPLOY_USER_PRIVATE_KEY }}
          ssh-passphrase: ${{ secrets.DEPLOY_PRIVATE_KEY_PASSPHRASE }}

      - name: Deploy to server
        uses: appleboy/scp-action@master
        with:
          host: 162.19.92.61
          username: deploy_user
          source: ./build
          target: /var/www/water-pilot  # Remplacez "water-pilot" par le nom de votre projet

